In [12]:
import os
import sys
import time
import yaml
import pandas as pd
import numpy as np
import re
import subprocess
import json

with open('../../config.local.yaml', 'r') as f:
    local_config = yaml.safe_load(f)


LOCAL_PATH = local_config['LOCAL_PATH']
R_PATH = local_config['R_PATH']

sys.path.append(os.path.join(LOCAL_PATH, "src/python"))

import writing_tools as wt
from utils import parse_casenum
import utils

from matplotlib import pyplot as plt
from scipy.spatial.distance import mahalanobis


plt.rcParams['font.family'] = 'Times New Roman'
plt.rcParams['font.size'] = 11

with open('../../config.local.yaml', 'r') as f:
    local_config = yaml.safe_load(f)
with open('../../config.yaml', 'r') as f:
    config = yaml.safe_load(f)

LOCAL_PATH = local_config['LOCAL_PATH']
DATA_PATH = local_config['DATA_PATH']
EMBEDDING_DIMENSION = config['EMBEDDING_DIMENSION']

rng = np.random.default_rng(12898)

N_CLUSTERS = 3
N_COMPONENTS = 10

In [13]:
# Output regression data

df = pd.read_parquet(os.path.join(DATA_PATH, "intermediate_data/cpc", "ologit_regression_data.parquet"))

In [14]:
for idx, row in df.iterrows():
    parsed_casenum = parse_casenum(row['title'])
    df.at[idx, 'prefix'] = parsed_casenum['prefix']
    df.at[idx, 'project_year'] = int(parsed_casenum['canonical_casenum'].split('-')[1])

df[['title', 'prefix', 'project_year']]

                                        title prefix  project_year
0                            CPC-2017-2406-DB    CPC        2017.0
1                       CPC-2014-2906-TDR-SPR    CPC        2014.0
2                        DIR-2017-4872-TOC-1A    DIR        2017.0
3                        DIR-2017-4451-TOC-1A    DIR        2017.0
4                 DIR-2016-4510-DB-SPR-WDI-1A    DIR        2016.0
..                                        ...    ...           ...
813                     CPC-2025-4636-CU3-WDI    CPC        2025.0
814                CPC-2025-3893-ZC-SPPE-SPPC    CPC        2025.0
815                  CPC-2025-537-CU3-ZV-SPPC    CPC        2025.0
816                     CPC-2025-1087-DB-VHCA    CPC        2025.0
817  CPC-2024-325-CU-MCUP-CUX-SPP-DRB-SPR-WDI    CPC        2024.0

[818 rows x 3 columns]

In [15]:
mask = (df['project_year'] >= 2010) & (df['project_year'] <= 2026)
pd.crosstab(df.loc[mask, 'project_year'], df.loc[mask, 'sfx_TOC'])

sfx_TOC       False  True
project_year
2012.0            1      0
2013.0            4      0
2014.0            9      0
2015.0           12      0
2016.0           77      0
2017.0           63      6
2018.0           68     24
2019.0           84     22
2020.0           62     17
2021.0           61     22
2022.0           64     13
2023.0           46     15
2024.0           42      3
2025.0           18      0

In [25]:
pd.crosstab(df['project_result'], df['sfx_TOC'], normalize='columns')

sfx_TOC                                             False     True
project_result
APPLICATION WITHDRAWN                            0.005747  0.000000
APPROVED                                         0.429598  0.450820
APPROVED WITH MAJOR CONDITIONS OR MODIFICATIONS  0.041667  0.024590
APPROVED WITH MINOR CONDITIONS OR MODIFICATIONS  0.366379  0.336066
DELAYED                                          0.142241  0.188525
DENIED                                           0.014368  0.000000

In [19]:
pd.crosstab(df['is_consent_calendar'], df['sfx_TOC'])

sfx_TOC              False  True
is_consent_calendar
False                  568    122
True                   128      0

In [20]:
pd.crosstab(df['prefix'], df['sfx_TOC'])

sfx_TOC  False  True
prefix
AA           7      0
ADM          8      0
CPC        556      0
DIR         37    119
ENV          1      0
TT           3      0
VTT         63      0
ZA          21      3

In [22]:
pd.crosstab(df['sfx_grp_APP'], df['sfx_TOC'])

sfx_TOC      False  True
sfx_grp_APP
False          559      0
True           137    122